### ISSUE TITLE
bug: failure to build 'LabelProvider' extension

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/generator-theia-extension#56]
**Description**

There is a build failure when attempting to generate a **LabelProvider** extension using the generator. The build failure is likely due to a breaking change upstream:

```
src/browser/aaa-contribution.ts(22,5): error TS2416: Property 'getIcon' in type 'AaaLabelProviderContribution' is not assignable to the same property in base type 'LabelProviderContribution'.
  Type '() => MaybePromise<string>' is not assignable to type '(element: object) => string | undefined'.
    Type 'MaybePromise<string>' is not assignable to type 'string | undefined'.
      Type 'Promise<string>' is not assignable to type 'string'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/vincentfugnitto/Desktop/vince/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:71999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:71999) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to Reproduce**

1. clone the repository
2. perform `yarn`
3. perform `npm link`
4. create a directory and perform `yo theia-extension`
5. select the `LabelProvider` option, and verify the build
6. the build should fail with the above error

cc @JonasHelming

**Comment by JonasHelming** [comment]
I refine the template quite a bit. That fixes the current issue, adapts the template to how label providers are done in Theia core and makes the template more robust for the future.
